### ISSUE TITLE
uvccamera not support Android 9

### ISSUE THREAD

**Issue by mafanwei** [Leessy/CoolKotlin#1]
I think that is some config missed.
from Android 9 ,uvccamera can open with origin api. But in some device are not support. Such as HuaWei.
We have to use uvccamera.

**Comment by Leessy** [comment]
> I think that is some config missed.
> 
> from Android 9 ,uvccamera can open with origin api. But in some device are not support. Such as HuaWei.
> 
> We have to use uvccamera.

You can provide logs that you can use for analysis

**Comment by mafanwei** [comment]
I notice that you already write:
```
 mUSBMonitor = USBMonitor(c, object : USBMonitor.OnDeviceConnectListener {
            override fun onAttach(device: UsbDevice?) {
                Log.d(
                    "CamerasMng",
                    "on Attach AnyDev ${device?.deviceName}  ${device?.vendorId}  ${device?.productId}"
                )
                device?.let {
                    if (pidFilter.contains(it.productId)) return//过滤指定pid设备
                    if (it.deviceClass == 239 && it.deviceSubclass == 2) {
                        Log.d(
                            "CamerasMng",
                            "on Attach CameraType ${device.deviceName}  ${device.vendorId}  ${device.productId}"
                        )
                        mUSBMonitor?.requestPermission(device)
                    }
                }
            }
```
But I did not receive it in the log.

**Comment by Leessy** [comment]
> I notice that you already write:
> 
> ```
> 
>  mUSBMonitor = USBMonitor(c, object : USBMonitor.OnDeviceConnectListener {
> 
>             override fun onAttach(device: UsbDevice?) {
> 
>                 Log.d(
> 
>                     "CamerasMng",
> 
>                     "on Attach AnyDev ${device?.deviceName}  ${device?.vendorId}  ${device?.productId}"
> 
>                 )
> 
>                 device?.let {
> 
>                     if (pidFilter.contains(it.productId)) return//过滤指定pid设备
> 
>                     if (it.deviceClass == 239 && it.deviceSubclass == 2) {
> 
>                         Log.d(
> 
>                             "CamerasMng",
> 
>                             "on Attach CameraType ${device.deviceName}  ${device.vendorId}  ${device.productId}"
> 
>                         )
> 
>                         mUSBMonitor?.requestPermission(device)
> 
>                     }
> 
>                 }
> 
>             }
> 
> ```
> 
> But I did not receive it in the log.


You can provide all logs of the app.

**Comment by mafanwei** [comment]
I test in HUAWEI P30，nothing happened. No log about uvc

**Comment by mafanwei** [comment]
After try sometimes, I gain this:
```
2020-04-02 20:35:17.650 17373-17486/? E/AndroidRuntime: FATAL EXCEPTION: USBMonitor
    Process: com.em3.mutliuvctest, PID: 17373
    java.lang.SecurityException: User has not given 10223/com.em3.mutliuvctest permission to access device /dev/bus/usb/002/002
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.hardware.usb.IUsbSerialReader$Stub$Proxy.getSerial(IUsbSerialReader.java:123)
        at android.hardware.usb.UsbDevice.getSerialNumber(UsbDevice.java:148)
        at com.serenegiant.usb.USBMonitor.getDeviceKeyName(USBMonitor.java:663)
        at com.serenegiant.usb.USBMonitor.getDeviceKey(USBMonitor.java:696)
        at com.serenegiant.usb.USBMonitor.updatePermission(USBMonitor.java:399)
        at com.serenegiant.usb.USBMonitor.hasPermission(USBMonitor.java:389)
        at com.serenegiant.usb.USBMonitor$2.run(USBMonitor.java:526)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.usb.UsbUserSettingsManager.checkPermission(libmapleservices.so:14092896)
        at com.android.server.usb.UsbSerialReader.getSerial(libmapleservices.so:16904376)
        at android.hardware.usb.IUsbSerialReader$Stub.onTransact(libmapleframework.so:18208228)
        at android.os.Binder.execTransactInternal(libmapleframework.so:8304892)
        at android.os.Binder.execTransact(libmapleframework.so:8304116)
```

**Comment by mafanwei** [comment]
How should I do?

**Comment by Leessy** [comment]
You should have more than one camera, but there is no delay when requesting permission, so you will only see the permission prompt for the last camera. I know there is a problem here, but we are all apps with system permission, and we will not prompt for permission confirmation, so I did not optimize here. I have time to perfect this. Can you do that?



发自我的iPhone


------------------ Original ------------------
